version: '3.8'

services:
  app:
    build: .
    container_name: medibot_app
    ports:
      - "8000:8000"
    environment:
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    env_file:
      - ./server/.env
    restart: always
    volumes:
      - ./server/uploaded_docs:/app/server/uploaded_docs

  nginx:
    image: nginx:latest
    container_name: medibot_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    restart: always
